## Unbind the default prefix key
#unbind C-b
#
## Set the new prefix key to Ctrl+A
#set-option -g prefix C-a
#
## Bind the new key to send the prefix command (necessary for nested sessions or sending the key to an inner program)
#bind-key C-a send-prefix
set-window-option -g xonoff off
